making changes and fixing scripts

diff --git a/linkup b/linkup
--- a/linkup
+++ b/linkup
@@ -1,8 +1,18 @@
 #!/bin/bash
-
+# ft:bash
 # this script will set links on cookbooks if they don't exist
 
-cookbook_names=$(ls $CHEF/cookbooks | awk '$1 ~ /^cookbook/ { print $0 }' | sed 's/cookbook-//')
-link_names=$(ls $HOME/repos/syms)
+link_dir="/Users/mgibson/repos/turner/syms/"
+cookbook_dir="/Users/mgibson/repos/turner/cookbooks/"
+cookbooks_list=$(for i in $(ls $cookbook_dir); do echo "${i##cookbook-}" ; done | xargs ) 
+
+for i in $cookbooks_list; do
+  ls $link_dir | grep -i $i > /dev/null 2>&1
+  if (( $? != 0 )); then
+    #logger -p local3.info "Missing link for $i"
+    echo "Missing link for ${i}"
+  fi
+done
+
 
 
